package DannyGermanSimulator;

import Entity.NPC_BigRock;
import Entity.NPC_Merchant;
import Entity.NPC_radish;
import data.Progress;
import monster.*;
import object.*;
import tile_interactive.IT_DestructibleWall;
import tile_interactive.IT_DryTree;
import tile_interactive.IT_MetalPlate;

public class AssetSetter {
    GamePanel gp;

    public AssetSetter(GamePanel gp){
        this.gp = gp;
    }
    public void setObject(){
        int mapNum = 0;
        int i = 0;
        gp.obj[mapNum][i] = new OBJ_Coin(gp);
        gp.obj[mapNum][i].worldX = gp.tileSize * 26;
        gp.obj[mapNum][i].worldY = gp.tileSize * 36;
        i++;
        gp.obj[mapNum][i] = new OBJ_Coin(gp);
        gp.obj[mapNum][i].worldX = gp.tileSize * 7;
        gp.obj[mapNum][i].worldY = gp.tileSize * 28;
        i++;
        gp.obj[mapNum][i] = new OBJ_Coin(gp);
        gp.obj[mapNum][i].worldX = gp.tileSize * 7;
        gp.obj[mapNum][i].worldY = gp.tileSize * 41;
        i++;
        gp.obj[mapNum][i] = new OBJ_Coin(gp);
        gp.obj[mapNum][i].worldX = gp.tileSize * 39;
        gp.obj[mapNum][i].worldY = gp.tileSize * 5;
        i++;
        gp.obj[mapNum][i] = new OBJ_Coin(gp);
        gp.obj[mapNum][i].worldX = gp.tileSize * 40;
        gp.obj[mapNum][i].worldY = gp.tileSize * 16;
        i++;
        gp.obj[mapNum][i] = new OBJ_Axe(gp);
        gp.obj[mapNum][i].worldX = gp.tileSize * 33;
        gp.obj[mapNum][i].worldY = gp.tileSize * 35;
        i++;
        gp.obj[mapNum][i] = new OBJ_Shield_Blue(gp);
        gp.obj[mapNum][i].worldX = gp.tileSize * 36;
        gp.obj[mapNum][i].worldY = gp.tileSize * 13;
        i++;
        gp.obj[mapNum][i] = new OBJ_Potion_Red(gp);
        gp.obj[mapNum][i].worldX = gp.tileSize * 35;
        gp.obj[mapNum][i].worldY = gp.tileSize * 13;


        mapNum = 3;
        i = 0;
        gp.obj[mapNum][i] = new OBJ_Boots(gp);
        gp.obj[mapNum][i].worldX = gp.tileSize * 148;
        gp.obj[mapNum][i].worldY = gp.tileSize * 170;
        i++;
        gp.obj[mapNum][i] = new OBJ_Door_Iron(gp);
        gp.obj[mapNum][i].worldX = gp.tileSize * 184;
        gp.obj[mapNum][i].worldY = gp.tileSize * 70;
        i++;
        gp.obj[mapNum][i] = new OBJ_Door_Iron(gp);
        gp.obj[mapNum][i].worldX = gp.tileSize * 148;
        gp.obj[mapNum][i].worldY = gp.tileSize * 172;
        i++;
        gp.obj[mapNum][i] = new OBJ_Door_Iron(gp);
        gp.obj[mapNum][i].worldX = gp.tileSize * 48;
        gp.obj[mapNum][i].worldY = gp.tileSize * 191;
        i++;
        gp.obj[mapNum][i] = new OBJ_Door(gp);
        gp.obj[mapNum][i].worldX = gp.tileSize * 39;
        gp.obj[mapNum][i].worldY = gp.tileSize * 162;
        i++;
        gp.obj[mapNum][i] = new OBJ_Door(gp);
        gp.obj[mapNum][i].worldX = gp.tileSize * 184;
        gp.obj[mapNum][i].worldY = gp.tileSize * 70;
        i++;
        gp.obj[mapNum][i] = new OBJ_Door(gp);
        gp.obj[mapNum][i].worldX = gp.tileSize * 184;
        gp.obj[mapNum][i].worldY = gp.tileSize * 65;
        i++;
        gp.obj[mapNum][i] = new OBJ_Door(gp);
        gp.obj[mapNum][i].worldX = gp.tileSize * 184;
        gp.obj[mapNum][i].worldY = gp.tileSize * 61;
        i++;
        gp.obj[mapNum][i] = new OBJ_Chest(gp);
        gp.obj[mapNum][i].setLoot(new OBJ_Potion_Red(gp));
        gp.obj[mapNum][i].worldX = gp.tileSize * 48;
        gp.obj[mapNum][i].worldY = gp.tileSize * 194;
        i++;
        gp.obj[mapNum][i] = new OBJ_Potion_Red(gp);
        gp.obj[mapNum][i].worldX = gp.tileSize * 23;
        gp.obj[mapNum][i].worldY = gp.tileSize * 230;
        i++;


        gp.obj[mapNum][i] = new OBJ_Lantern(gp);
        gp.obj[mapNum][i].worldX = gp.tileSize * 25;
        gp.obj[mapNum][i].worldY = gp.tileSize * 230;
        i++;
    }
    public void setNPC(){
        int mapNum = 0;
        int i = 0;
        gp.npc[mapNum][i] = new NPC_radish(gp);
        gp.npc[mapNum][i].worldX = gp.tileSize * 20;
        gp.npc[mapNum][i].worldY = gp.tileSize * 20;
        i++;


        mapNum = 1;
        i = 0;
        gp.npc[mapNum][i] = new NPC_Merchant(gp);
        gp.npc[mapNum][i].worldX = gp.tileSize * 12;
        gp.npc[mapNum][i].worldY = gp.tileSize * 7;
        i++;

        mapNum = 2;
        i = 0;
        gp.npc[mapNum][i] = new NPC_radish(gp);
        gp.npc[mapNum][i].worldX = gp.tileSize * 27;
        gp.npc[mapNum][i].worldY = gp.tileSize * 117;
        i++;
        gp.npc[mapNum][i] = new NPC_Merchant(gp);
        gp.npc[mapNum][i].worldX = gp.tileSize * 153;
        gp.npc[mapNum][i].worldY = gp.tileSize * 58;
        i++;

        mapNum = 3;
        i = 0;
        gp.npc[mapNum][i] = new NPC_Merchant(gp);
        gp.npc[mapNum][i].worldX = gp.tileSize * 22;
        gp.npc[mapNum][i].worldY = gp.tileSize * 231;
        i++;
        gp.npc[mapNum][i] = new NPC_BigRock(gp);
        gp.npc[mapNum][i].worldX = gp.tileSize * 24;
        gp.npc[mapNum][i].worldY = gp.tileSize * 231;
        i++;
        gp.npc[mapNum][i] = new NPC_BigRock(gp);
        gp.npc[mapNum][i].worldX = gp.tileSize * 42;
        gp.npc[mapNum][i].worldY = gp.tileSize * 164;
        i++;
    }
    public void setMonster(){
        int mapNum = 0;
        int i = 0;
        gp.monster[mapNum][i] = new MON_Bat_Fire(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 36;
        gp.monster[mapNum][i].worldY = gp.tileSize * 13;
        i++;
        gp.monster[mapNum][i] = new MON_Bat_Fire(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 39;
        gp.monster[mapNum][i].worldY = gp.tileSize * 12;
        i++;
        gp.monster[mapNum][i] = new MON_Bat_Fire(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 27;
        gp.monster[mapNum][i].worldY = gp.tileSize * 13;
        i++;
        gp.monster[mapNum][i] = new MON_Bat_Fire(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 35;
        gp.monster[mapNum][i].worldY = gp.tileSize * 12;
        i++;
        gp.monster[mapNum][i] = new MON_Bat_Fire(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 28;
        gp.monster[mapNum][i].worldY = gp.tileSize * 15;
        i++;
        gp.monster[mapNum][i] = new MON_Bat_Fire(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 42;
        gp.monster[mapNum][i].worldY = gp.tileSize * 12;
        i++;
        gp.monster[mapNum][i] = new MON_Bat_Fire(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 39;
        gp.monster[mapNum][i].worldY = gp.tileSize * 10;
        i++;
        gp.monster[mapNum][i] = new MON_Bat_Fire(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 30;
        gp.monster[mapNum][i].worldY = gp.tileSize * 12;
        i++;

        mapNum = 2;
        i = 0;
        gp.monster[mapNum][i] = new MON_Orc(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 186;
        gp.monster[mapNum][i].worldY = gp.tileSize * 189;
        i++;
        gp.monster[mapNum][i] = new MON_Orc(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 185;
        gp.monster[mapNum][i].worldY = gp.tileSize * 189;
        i++;
        gp.monster[mapNum][i] = new MON_Orc(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 187;
        gp.monster[mapNum][i].worldY = gp.tileSize * 189;
        i++;
        //First Area
        gp.monster[mapNum][i] = new MON_Slime(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 48;
        gp.monster[mapNum][i].worldY = gp.tileSize * 105;
        i++;
        gp.monster[mapNum][i] = new MON_Slime(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 41;
        gp.monster[mapNum][i].worldY = gp.tileSize * 104;
        i++;
        gp.monster[mapNum][i] = new MON_Slime(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 46;
        gp.monster[mapNum][i].worldY = gp.tileSize * 96;
        i++;
        gp.monster[mapNum][i] = new MON_Slime(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 51;
        gp.monster[mapNum][i].worldY = gp.tileSize * 93;
        i++;
        //second area
        gp.monster[mapNum][i] = new MON_RedSlime(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 86;
        gp.monster[mapNum][i].worldY = gp.tileSize * 101;
        i++;
        gp.monster[mapNum][i] = new MON_RedSlime(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 79;
        gp.monster[mapNum][i].worldY = gp.tileSize * 107;
        i++;
        gp.monster[mapNum][i] = new MON_RedSlime(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 93;
        gp.monster[mapNum][i].worldY = gp.tileSize * 111;
        i++;
        gp.monster[mapNum][i] = new MON_RedSlime(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 80;
        gp.monster[mapNum][i].worldY = gp.tileSize * 110;
        i++;
        //Third area
        gp.monster[mapNum][i] = new MON_RedSlime(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 79;
        gp.monster[mapNum][i].worldY = gp.tileSize * 73;
        i++;
        gp.monster[mapNum][i] = new MON_Slime(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 68;
        gp.monster[mapNum][i].worldY = gp.tileSize * 76;
        i++;
        gp.monster[mapNum][i] = new MON_BlueSlime(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 84;
        gp.monster[mapNum][i].worldY = gp.tileSize * 77;
        i++;

        //fourth area
        gp.monster[mapNum][i] = new MON_RedSlime(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 46;
        gp.monster[mapNum][i].worldY = gp.tileSize * 76;
        i++;
        gp.monster[mapNum][i] = new MON_BlueSlime(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 32;
        gp.monster[mapNum][i].worldY = gp.tileSize * 80;
        i++;
        gp.monster[mapNum][i] = new MON_RedSlime(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 33;
        gp.monster[mapNum][i].worldY = gp.tileSize * 73;
        i++;
        gp.monster[mapNum][i] = new MON_cock(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 137;
        gp.monster[mapNum][i].worldY = gp.tileSize * 60;
        i++;
        gp.monster[mapNum][i] = new MON_cock(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 132;
        gp.monster[mapNum][i].worldY = gp.tileSize * 25;
        i++;
        gp.monster[mapNum][i] = new MON_cock(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 34;
        gp.monster[mapNum][i].worldY = gp.tileSize * 27;
        i++;


        mapNum = 3;
        i = 0;
        //first area
        gp.monster[mapNum][i] = new MON_Spider(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 26;
        gp.monster[mapNum][i].worldY = gp.tileSize * 230;
        i++;
        gp.monster[mapNum][i] = new MON_Spider(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 40;
        gp.monster[mapNum][i].worldY = gp.tileSize * 230;
        i++;
        gp.monster[mapNum][i] = new MON_Spider(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 57;
        gp.monster[mapNum][i].worldY = gp.tileSize * 218;
        i++;
        gp.monster[mapNum][i] = new MON_Spider(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 61;
        gp.monster[mapNum][i].worldY = gp.tileSize * 218;
        i++;
        gp.monster[mapNum][i] = new MON_RedSlime(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 77;
        gp.monster[mapNum][i].worldY = gp.tileSize * 209;
        i++;
        gp.monster[mapNum][i] = new MON_RedSlime(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 77;
        gp.monster[mapNum][i].worldY = gp.tileSize * 189;
        i++;
        gp.monster[mapNum][i] = new MON_Spider(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 56;
        gp.monster[mapNum][i].worldY = gp.tileSize * 189;
        i++;

        //second area
        gp.monster[mapNum][i] = new MON_Orc(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 82;
        gp.monster[mapNum][i].worldY = gp.tileSize * 119;
        i++;
        gp.monster[mapNum][i] = new MON_Spider(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 85;
        gp.monster[mapNum][i].worldY = gp.tileSize * 129;
        i++;
        gp.monster[mapNum][i] = new MON_RedSlime(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 77;
        gp.monster[mapNum][i].worldY = gp.tileSize * 145;
        i++;
        gp.monster[mapNum][i] = new MON_Orc(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 70;
        gp.monster[mapNum][i].worldY = gp.tileSize * 111;
        i++;
        gp.monster[mapNum][i] = new MON_Orc(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 73;
        gp.monster[mapNum][i].worldY = gp.tileSize * 85;
        i++;
        gp.monster[mapNum][i] = new MON_Orc(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 68;
        gp.monster[mapNum][i].worldY = gp.tileSize * 99;
        i++;
        gp.monster[mapNum][i] = new MON_Orc(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 73;
        gp.monster[mapNum][i].worldY = gp.tileSize * 86;
        i++;


        //third area
        gp.monster[mapNum][i] = new MON_Zombie(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 52;
        gp.monster[mapNum][i].worldY = gp.tileSize * 58;
        i++;
        gp.monster[mapNum][i] = new MON_Zombie(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 52;
        gp.monster[mapNum][i].worldY = gp.tileSize * 53;
        i++;
        gp.monster[mapNum][i] = new MON_Zombie(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 65;
        gp.monster[mapNum][i].worldY = gp.tileSize * 56;
        i++;
        gp.monster[mapNum][i] = new MON_Zombie(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 69;
        gp.monster[mapNum][i].worldY = gp.tileSize * 46;
        i++;
        gp.monster[mapNum][i] = new MON_Zombie(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 75;
        gp.monster[mapNum][i].worldY = gp.tileSize * 35;
        i++;
        gp.monster[mapNum][i] = new MON_Orc(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 77;
        gp.monster[mapNum][i].worldY = gp.tileSize * 56;
        i++;
        gp.monster[mapNum][i] = new MON_Zombie(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 86;
        gp.monster[mapNum][i].worldY = gp.tileSize * 54;
        i++;
        gp.monster[mapNum][i] = new MON_Zombie(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 100;
        gp.monster[mapNum][i].worldY = gp.tileSize * 50;
        i++;
        gp.monster[mapNum][i] = new MON_Zombie(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 105;
        gp.monster[mapNum][i].worldY = gp.tileSize * 47;
        i++;
        gp.monster[mapNum][i] = new MON_Zombie(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 101;
        gp.monster[mapNum][i].worldY = gp.tileSize * 54;
        i++;
        gp.monster[mapNum][i] = new MON_Zombie(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 95;
        gp.monster[mapNum][i].worldY = gp.tileSize * 62;
        i++;

//        gp.monster[mapNum][i] = new MON_Slime(gp);
//        gp.monster[mapNum][i].worldX = gp.tileSize * 28;
//        gp.monster[mapNum][i].worldY = gp.tileSize * 230;
//        i++;
//        gp.monster[mapNum][i] = new MON_Slime(gp);
//        gp.monster[mapNum][i].worldX = gp.tileSize * 50;
//        gp.monster[mapNum][i].worldY = gp.tileSize * 229;
//        i++;
//        gp.monster[mapNum][i] = new MON_Slime(gp);
//        gp.monster[mapNum][i].worldX = gp.tileSize * 51;
//        gp.monster[mapNum][i].worldY = gp.tileSize * 229;
//        i++;
//        gp.monster[mapNum][i] = new MON_Slime(gp);
//        gp.monster[mapNum][i].worldX = gp.tileSize * 44;
//        gp.monster[mapNum][i].worldY = gp.tileSize * 218;
//        i++;
//        gp.monster[mapNum][i] = new MON_Slime(gp);
//        gp.monster[mapNum][i].worldX = gp.tileSize * 61;
//        gp.monster[mapNum][i].worldY = gp.tileSize * 202;
//        i++;
//        gp.monster[mapNum][i] = new MON_Slime(gp);
//        gp.monster[mapNum][i].worldX = gp.tileSize * 77;
//        gp.monster[mapNum][i].worldY = gp.tileSize * 209;
//        i++;
//        gp.monster[mapNum][i] = new MON_Slime(gp);
//        gp.monster[mapNum][i].worldX = gp.tileSize * 75;
//        gp.monster[mapNum][i].worldY = gp.tileSize * 212;
//        i++;
//        gp.monster[mapNum][i] = new MON_Slime(gp);
//        gp.monster[mapNum][i].worldX = gp.tileSize * 71;
//        gp.monster[mapNum][i].worldY = gp.tileSize * 189;
//        i++;
//        gp.monster[mapNum][i] = new MON_Slime(gp);
//        gp.monster[mapNum][i].worldX = gp.tileSize * 50;
//        gp.monster[mapNum][i].worldY = gp.tileSize * 188;
//        i++;
//        gp.monster[mapNum][i] = new MON_Slime(gp);
//        gp.monster[mapNum][i].worldX = gp.tileSize * 50;
//        gp.monster[mapNum][i].worldY = gp.tileSize * 189;
//        i++;
//        gp.monster[mapNum][i] = new MON_Slime(gp);
//        gp.monster[mapNum][i].worldX = gp.tileSize * 50;
//        gp.monster[mapNum][i].worldY = gp.tileSize * 190;
//        i++;
//        gp.monster[mapNum][i] = new MON_Slime(gp);
//        gp.monster[mapNum][i].worldX = gp.tileSize * 35;
//        gp.monster[mapNum][i].worldY = gp.tileSize * 171;
//        i++;
//        gp.monster[mapNum][i] = new MON_Slime(gp);
//        gp.monster[mapNum][i].worldX = gp.tileSize * 43;
//        gp.monster[mapNum][i].worldY = gp.tileSize * 171;
//        i++;
//        gp.monster[mapNum][i] = new MON_Slime(gp);
//        gp.monster[mapNum][i].worldX = gp.tileSize * 39;
//        gp.monster[mapNum][i].worldY = gp.tileSize * 174;
//        i++;
//        gp.monster[mapNum][i] = new MON_Bat_Fire(gp);
//        gp.monster[mapNum][i].worldX = gp.tileSize * 39;
//        gp.monster[mapNum][i].worldY = gp.tileSize * 171;
//        i++;
//        gp.monster[mapNum][i] = new MON_Bat(gp);
//        gp.monster[mapNum][i].worldX = gp.tileSize * 36;
//        gp.monster[mapNum][i].worldY = gp.tileSize * 164;
//        i++;
        if(!Progress.skeletonLordDefeated){
            gp.monster[mapNum][i] = new MON_SkeletonLord(gp);
            gp.monster[mapNum][i].worldX = gp.tileSize * 148;
            gp.monster[mapNum][i].worldY = gp.tileSize * 192;
            i++;
        }
    }
    public void setInteractiveTile() {
        int mapNum = 0;
        int i = 0;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,18,17); i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,19,17); i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,20,17); i++;


        gp.iTile[mapNum][i] = new IT_DryTree(gp,5,26); i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,6,26); i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,7,26); i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,8,26); i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,5,29); i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,6,29); i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,7,29); i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,8,29); i++;

        mapNum = 3;
        i = 0;
        gp.iTile[mapNum][i] = new IT_DestructibleWall(gp,44,229); i++;
        gp.iTile[mapNum][i] = new IT_DestructibleWall(gp,45,229); i++;
        gp.iTile[mapNum][i] = new IT_DestructibleWall(gp,44,228); i++;
        gp.iTile[mapNum][i] = new IT_DestructibleWall(gp,45,228); i++;
        gp.iTile[mapNum][i] = new IT_MetalPlate(gp,45,164); i++;
    }
}
